# Generated by Django 4.1 on 2022-08-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('yr', models.IntegerField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
    ]
