# Generated by Django 4.1 on 2022-08-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_searched', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_stamp', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('max_temp', models.FloatField(blank=True, default=None, null=True)),
                ('min_temp', models.FloatField(blank=True, default=None, null=True)),
                ('precipitation', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
